#!/bin/bash

## This file is part of Whonix.
## Copyright (C) 2012 - 2014 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

set -x

if [ -f /usr/lib/pre.bsh ]; then
   source /usr/lib/pre.bsh
fi

set -e
set -o pipefail

package_name="$(basename $( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd ))"

command -v dpkg-parsechangelog >/dev/null
OIFS="${IFS}"
NIFS=$'\n'
IFS="${NIFS}"
for line in $(dpkg-parsechangelog); do
   IFS="${OIFS}"
   read -r first second _ <<< "$line"
   first="${first,,}"
   if [ "$first" = "version:" ]; then
      version="$second"
      break
   fi
done
IFS="${OIFS}"

version="$(echo "$version" | tr "-" " ")"
version="$(echo "$version" | awk '{print $1}')"

if [ "$version" = "" ]; then
   true "ERROR: variable version is empty."
   exit 1
fi

./clean

## Explicitly set access time, so we end up with a deterministic debian.tar.gz file
shopt -s globstar
touch -t "201308151102.35" ./debian
touch -t "201308151102.35" ./debian/**
shopt -u globstar

rm --force "../${package_name}_${version}.orig.tar.gz"

git archive \
   --format=tar HEAD \
   | gzip -n > "../${package_name}_${version}.orig.tar.gz"

ls -la "../${package_name}_${version}.orig.tar.gz"

debuild \
   --rootcmd="debian/gain-root-command" \
   -sa \
   ${1+"$@"}
